/**
 * Módulo de Datos Iniciales para el Calendario Ciclista de Chile
 */

export const REGIONS_CHILE = [
  "Todas las regiones",
  "Región de Arica y Parinacota",
  "Región de Tarapacá",
  "Región de Antofagasta",
  "Región de Atacama",
  "Región de Coquimbo",
  "Región de Valparaíso",
  "Región Metropolitana de Santiago",
  "Región del Libertador General Bernardo O'Higgins",
  "Región del Maule",
  "Región de Ñuble",
  "Región del Biobío",
  "Región de La Araucanía",
  "Región de Los Ríos",
  "Región de Los Lagos",
  "Región de Aysén del General Carlos Ibáñez del Campo",
  "Región de Magallanes y de la Antártica Chilena"
];

export const INITIAL_RACES = [
  {
    id: "race-001",
    name: "Gran Fondo Valle del Elqui",
    discipline: "Ruta",
    date: "2026-10-15",
    month: "Octubre",
    displayDate: "15 de Octubre, 2026",
    region: "Región de Coquimbo",
    city: "Vicuña",
    distance: "120 km",
    elevation: "1850 m",
    price: 35000,
    isFree: false,
    status: "Inscripciones Abiertas",
    organizer: "Club Ciclismo Coquimbo",
    registrationUrl: "https://ejemplo.cl/registro/gf-elqui",
    heroImage: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=1200&q=80",
    description: "Una imperdible competencia de gran fondo recorriendo los imponentes paisajes astronómicos y viñedos del Valle del Elqui con llegada en altitud.",
    categories: ["Elite", "Master A", "Master B", "Master C", "Amateur", "Damas Elite", "Damas Master"],
    participants: 340
  },
  {
    id: "race-002",
    name: "Desafío Transandes MTB Chiloé",
    discipline: "MTB",
    date: "2026-11-20",
    month: "Noviembre",
    displayDate: "20 - 22 de Noviembre, 2026",
    region: "Región de Los Lagos",
    city: "Castro",
    distance: "85 km",
    elevation: "2400 m",
    price: 45000,
    isFree: false,
    status: "Inscripciones Abiertas",
    organizer: "Austral Bike Chile",
    registrationUrl: "https://ejemplo.cl/registro/transandes-chiloe",
    heroImage: "https://images.unsplash.com/photo-1517649763962-0c623266010b?auto=format&fit=crop&w=1200&q=80",
    description: "Tres días de puro XCM cruzando los bosques nativos, palafitos y senderos ancestrales de la mítica Isla Grande de Chiloé.",
    categories: ["Pro Elite", "Varones A", "Varones B", "Damas Pro", "Duplas Mixtas"],
    participants: 210
  },
  {
    id: "race-003",
    name: "Gravel Pacífico Central",
    discipline: "Gravel",
    date: "2026-09-05",
    month: "Septiembre",
    displayDate: "5 de Septiembre, 2026",
    region: "Región de Valparaíso",
    city: "Zapallar",
    distance: "105 km",
    elevation: "1400 m",
    price: 28000,
    isFree: false,
    status: "Próximamente",
    organizer: "Gravel Chile Club",
    registrationUrl: "https://ejemplo.cl/registro/gravel-pacifico",
    heroImage: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80",
    description: "Aventura costera por caminos rurales de tierra, huertos de paltos y acantilados sobre el Océano Pacífico.",
    categories: ["Gravel Open", "Gravel Master", "Gravel Damas", "E-Bike Gravel"],
    participants: 180
  },
  {
    id: "race-004",
    name: "Copa Pista Velódromo Peñalolén",
    discipline: "Pista",
    date: "2026-08-12",
    month: "Agosto",
    displayDate: "12 de Agosto, 2026",
    region: "Región Metropolitana de Santiago",
    city: "Peñalolén",
    distance: "20 km",
    elevation: "0 m",
    price: 0,
    isFree: true,
    status: "Inscripciones Abiertas",
    organizer: "Federación Nacional de Ciclismo",
    registrationUrl: "https://ejemplo.cl/registro/copa-pista-penalolen",
    heroImage: "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=1200&q=80",
    description: "Competencia de velocidad, persecución y prueba de eliminación en la madera bajo techo del Velódromo de Peñalolén.",
    categories: ["Junior", "Sub-23", "Elite Varones", "Elite Damas"],
    participants: 95
  },
  {
    id: "race-005",
    name: "Nacional BMX Racing Ñuñoa",
    discipline: "BMX",
    date: "2026-10-28",
    month: "Octubre",
    displayDate: "28 de Octubre, 2026",
    region: "Región Metropolitana de Santiago",
    city: "Ñuñoa",
    distance: "400 m",
    elevation: "5 m",
    price: 15000,
    isFree: false,
    status: "Inscripciones Abiertas",
    organizer: "BMX Chile Federation",
    registrationUrl: "https://ejemplo.cl/registro/nacional-bmx",
    heroImage: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80",
    description: "Fecha clasificatoria nacional de BMX Racing con arranques explosivos en el partido técnico del Estadio Nacional.",
    categories: ["Challenger 7-8", "Challenger 13-14", "Junior", "Elite Pro"],
    participants: 150
  },
  {
    id: "race-006",
    name: "Chile Zwift Virtual League - Fecha 4",
    discipline: "Virtual",
    date: "2026-08-30",
    month: "Agosto",
    displayDate: "30 de Agosto, 2026",
    region: "Todas las regiones",
    city: "Online (Zwift)",
    distance: "45 km",
    elevation: "650 m",
    price: 0,
    isFree: true,
    status: "Inscripciones Abiertas",
    organizer: "E-Sports Cycling Chile",
    registrationUrl: "https://ejemplo.cl/registro/zwift-chile-f4",
    heroImage: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80",
    description: "Competencia virtual oficial sincrónica por potencia e-cycling con transmisión en vivo y ránkings acumulativos.",
    categories: ["Cat A (+4.0 W/kg)", "Cat B (3.2-3.9 W/kg)", "Cat C (2.5-3.1 W/kg)", "Damas Open"],
    participants: 420
  },
  {
    id: "race-007",
    name: "Ascenso Farellones Challenge",
    discipline: "Ruta",
    date: "2026-11-08",
    month: "Noviembre",
    displayDate: "8 de Noviembre, 2026",
    region: "Región Metropolitana de Santiago",
    city: "Lo Barnechea",
    distance: "32 km",
    elevation: "1980 m",
    price: 32000,
    isFree: false,
    status: "Cupos Agotados",
    organizer: "Andes Cycling Promotions",
    registrationUrl: "https://ejemplo.cl/registro/ascenso-farellones",
    heroImage: "https://images.unsplash.com/photo-1517649763962-0c623266010b?auto=format&fit=crop&w=1200&q=80",
    description: "El mítico desafío de 40 curvas desde la curva 0 hasta Farellones. La escalada en ruta más emblemática de la capital.",
    categories: ["Elite", "Master A", "Master B", "Master C", "Damas", "Cicloturismo"],
    participants: 600
  },
  {
    id: "race-008",
    name: "Epic Araucanía MTB Marathon",
    discipline: "MTB",
    date: "2026-12-05",
    month: "Diciembre",
    displayDate: "5 de Diciembre, 2026",
    region: "Región de La Araucanía",
    city: "Pucón",
    distance: "70 km",
    elevation: "2100 m",
    price: 38000,
    isFree: false,
    status: "Próximamente",
    organizer: "Volcano Bike Race",
    registrationUrl: "https://ejemplo.cl/registro/epic-araucania",
    heroImage: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80",
    description: "Ruta volcánica a los pies del Volcán Villarrica, sorteando arena volcánica, senderos de araucarias y lechos de ríos.",
    categories: ["XCM Elite", "XCM Master", "XCM Damas", "XCO Promocional"],
    participants: 280
  }
];
